# Generated by Django 2.2.5 on 2019-09-20 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBadge',
            fields=[
                ('badge_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
            ],
            options={
                'db_table': 'game_badge',
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('user_points_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('badge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicalapp.GameBadge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_points',
            },
        ),
    ]
