# Generated by Django 2.2.5 on 2019-09-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0003_auto_20190921_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpoints',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='userpoints',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='badge',
        ),
        migrations.DeleteModel(
            name='GameBadge',
        ),
        migrations.DeleteModel(
            name='UserPoints',
        ),
    ]
